package main

import (
	"net/http"
	"strings"
)

func main() {
	// Generated by curl-to-Go: https://mholt.github.io/curl-to-go
	body := strings.NewReader(`payload={"username": "バッチ君", "text": "アプリを起動しました！", "icon_emoji": ":shipit:"}`)
	req, err := http.NewRequest("POST", "https://hooks.slack.com/services/xxxxxxxx", body)
	if err != nil {
		panic(err)
	}
	req.Header.Set("Content-Type", "application/x-www-form-urlencoded")

	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		panic(err)
	}
	defer resp.Body.Close()
}
